const state = { model: null, filter: "all" };
const $ = (id) => document.getElementById(id);
const statusClass = (value) => value.startsWith("active") ? "healthy" : value.startsWith("error") ? "error" : value.startsWith("warning") ? "warning" : "unknown";
const label = (value) => ({"active/healthy":"Healthy / aktiv","inactive/stopped":"Inaktiv / gestoppt","warning/degraded":"Warnung / degradiert","error/unhealthy":"Fehler / ungesund","unknown/stale":"Unbekannt / veraltet"}[value] || value);
function render() {
  const m = state.model; const items = m.integrations.filter((item) => state.filter === "all" || item.id === state.filter);
  $("updated").textContent = `Zuletzt aktualisiert ${new Date(m.generatedAt).toLocaleTimeString("de-DE", {hour:"2-digit", minute:"2-digit", second:"2-digit"})}`;
  $("connection-count").textContent = `${m.integrations.length} erkannt`;
  $("connections").innerHTML = items.length ? items.map((item) => `<article class="card"><div class="card-top"><div><div class="type">${item.type}</div><h3>${item.name}</h3></div><span class="badge ${statusClass(item.healthStatus)}">${label(item.healthStatus)}</span></div><p class="reason">${item.statusReason}</p><dl class="meta"><div><dt>Konfiguration</dt><dd>${item.configured ? "vorhanden" : "nicht konfiguriert"}</dd></div><div><dt>Verbindung</dt><dd>${item.endpointClass || "nicht verfügbar"}</dd></div><div><dt>Runtime</dt><dd>${label(item.runtimeStatus)}</dd></div><div><dt>Diagnose</dt><dd>${item.diagnosticsAvailable ? "verfügbar" : "nicht verfügbar"}</dd></div></dl></article>`).join("") : `<div class="empty">Keine konfigurierte Verbindung für dieses Projekt. Die verfügbaren Einrichtungsschritte stehen weiter unten.</div>`;
  const tabs = [{id:"all", name:"Übersicht"}, ...m.integrations.map((item) => ({id:item.id, name:item.name})), {id:"setup", name:"Skill & Client Integration"}];
  $("tabs").innerHTML = tabs.map((tab) => `<button class="tab ${state.filter === tab.id ? "active" : ""}" data-filter="${tab.id}">${tab.name}</button>`).join("");
  document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { state.filter = tab.dataset.filter === "setup" ? "all" : tab.dataset.filter; render(); $("guides").scrollIntoView({behavior:"smooth", block:"center"}); }));
  $("notices").innerHTML = m.notices.length ? m.notices.map((n) => `<div class="notice"><strong>${n.title}</strong><p>${n.body}</p></div>`).join("") : `<div class="empty">Keine Warnungen aus den verfügbaren lokalen Statusquellen.</div>`;
  renderEvents(false); renderGuides(m.setupGuides); renderSkill(m.skill);
}
function renderEvents(all) { const events = all ? state.model.events : state.model.events.slice(-5); $("events").innerHTML = events.length ? events.map((e) => `<div class="event ${e.severity === "error" ? "error" : ""}"><div class="event-head"><span>${e.severity.toUpperCase()} · ${e.source}</span><span>${new Date(e.timestamp).toLocaleTimeString("de-DE")}</span></div>${e.message}</div>`).join("") : `<div class="empty">Keine sicheren Ereignisse aus den erlaubten Logquellen.</div>`; $("show-logs").textContent = all ? "Weniger anzeigen" : "Alle Logs anzeigen"; }
function renderGuides(guides) { $("guides").innerHTML = guides.map((g) => `<div class="guide"><h3>${g.title}</h3><ol>${g.steps.map((step) => `<li>${step}</li>`).join("")}</ol><a href="https://github.com/GeektankLabs/opencode-vm/blob/main/${g.docs}" target="_blank" rel="noreferrer">Dokumentation öffnen</a></div>`).join(""); }
function renderSkill(skill) { $("skill").innerHTML = skill.revision ? `<p><strong>${skill.name}</strong><br>Revision ${skill.revision}. Instruction-only Paket, getrennt von der MCP-Verbindung.</p><div class="checksum">SHA-256: ${skill.sha256}</div><div class="skill-actions"><a href="${skill.download}" target="_blank" rel="noreferrer">Latest herunterladen</a><a href="${skill.docs}" target="_blank" rel="noreferrer">Installation</a></div>` : `<p>Keine Skill-Metadaten verfügbar. Die Paketquelle ist im Repository unter integrations/chatgpt dokumentiert.</p>`; }
async function load() { try { const response = await fetch("/api/read-model", {cache:"no-store"}); if (!response.ok) throw new Error(); state.model = await response.json(); render(); } catch { $("connections").innerHTML = `<div class="empty">Read-Model konnte nicht geladen werden. Prüfe den Hub-Healthcheck.</div>`; $("updated").textContent = "Status nicht verfügbar"; } }
$("refresh").addEventListener("click", load); $("show-logs").addEventListener("click", () => renderEvents($("show-logs").textContent.startsWith("Alle"))); load();
